# -*- coding: utf-8 -*-
"""Captcha_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPZEvbcy1gDv3ap4yntLf6toUEBrQWlV
"""

from PIL import Image
import pandas as pd
import cv2
from google.colab.patches import cv2_imshow
from google.colab import files
import os

def replace_pixels_with_white(image_path, coordinates_csv, output_path):

    # Load the image
    img = Image.open(image_path)

    # Load pixel coordinates from CSV
    coordinates_df = pd.read_csv(coordinates_csv, header=None, names=['coordinates'])

    # Replace pixels with white color
    for index, row in coordinates_df.iterrows():
        # Split the coordinates string by comma and convert to integers
        x, y = map(int, row['coordinates'].split(','))
        img.putpixel((x, y), (255, 255, 255))

    # Save the modified image
    img.save(output_path)
    print(f"Modified image saved as: {output_path}")

def process_uploaded_images():

    image_path = '/content/output_image.jpg'

    # Load the grayscale image
    gray_image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # Adjust brightness and contrast
    alpha = 1.5  # Brightness control (1.0 - original, >1.0 brighter, <1.0 darker)
    beta = 10    # Contrast control (0 - original, >0 more contrast, <0 less contrast)
    adjusted_image = cv2.convertScaleAbs(gray_image, alpha=alpha, beta=beta)

    # Sharpen the image using unsharp masking
    blurred_image = cv2.GaussianBlur(adjusted_image, (0, 0), 3)  # Apply Gaussian blur
    sharpened_image = cv2.addWeighted(adjusted_image, 1.5, blurred_image, -0.5, 0)

    # Fade the lines using bilateral filtering
    smoothed_image_result = cv2.bilateralFilter(sharpened_image, 9, 75, 75)

    # Save the smoothed image
    smoothed_image_path = '/content/final_image.jpg'
    cv2.imwrite(smoothed_image_path, smoothed_image_result)
    print(f"Smoothed image saved as: {smoothed_image_path}")

    # Display the final result
    cv2_imshow(smoothed_image_result)

# Example usage of pixel replacement
def main():
    # Replace pixels in an image
    image_path = '/content/24.jpg'
    coordinates_csv = '/content/pixels.csv'
    output_path = '/content/output_image.jpg'
    replace_pixels_with_white(image_path, coordinates_csv, output_path)

    # Process the modified image
    process_uploaded_images()

if __name__ == "__main__":
    main()

